"""Schema-level guarantees: pgvector wiring, migration/model agreement, seeds."""

from __future__ import annotations

import asyncio

import pytest
from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.models import EMBEDDING_DIM, IngredientCategory, Recipe

pytestmark = pytest.mark.db


async def test_extensions_are_installed(session: AsyncSession) -> None:
    installed = set((await session.scalars(text("SELECT extname FROM pg_extension"))).all())
    assert {"vector", "pg_trgm"} <= installed


async def test_ingredient_categories_are_seeded(session: AsyncSession) -> None:
    count = await session.scalar(select(func.count()).select_from(IngredientCategory))
    assert count is not None and count >= 15
    codes = set((await session.scalars(select(IngredientCategory.code))).all())
    # Both M4 coefficient categories that the M1 sketch's comment omitted.
    assert {"мясо", "птица", "макароны", "крупы"} <= codes


async def test_vector_column_round_trips_through_asyncpg(session: AsyncSession) -> None:
    """Proves the pgvector + asyncpg + SQLAlchemy wiring.

    Note there is deliberately no `register_vector` event listener anywhere:
    pgvector's SQLAlchemy type serialises vectors as text, and registering
    asyncpg's binary codec makes the two layers fight. This test fails loudly if
    somebody later "helpfully" adds it.
    """
    vector = [0.1] * EMBEDDING_DIM
    session.add(Recipe(title="тестовый рецепт", servings=2, embedding=vector))
    await session.flush()

    stored = await session.scalar(select(Recipe.embedding).where(Recipe.title == "тестовый рецепт"))
    assert stored is not None
    assert len(stored) == EMBEDDING_DIM
    assert stored[0] == pytest.approx(0.1, abs=1e-6)


async def test_hnsw_index_orders_by_cosine_distance(session: AsyncSession) -> None:
    near = [1.0] + [0.0] * (EMBEDDING_DIM - 1)
    far = [0.0] * (EMBEDDING_DIM - 1) + [1.0]
    session.add_all(
        [
            Recipe(title="близкий", servings=1, embedding=near),
            Recipe(title="далёкий", servings=1, embedding=far),
        ]
    )
    await session.flush()

    ordered = (
        await session.scalars(
            select(Recipe.title)
            .where(Recipe.embedding.is_not(None))
            .order_by(Recipe.embedding.cosine_distance(near))
            .limit(2)
        )
    ).all()
    assert ordered[0] == "близкий"


async def test_source_url_is_unique(session: AsyncSession) -> None:
    """M2's idempotency criterion depends on this constraint existing."""
    url = "https://example.test/recipe/1"
    session.add(Recipe(title="первый", servings=1, source_url=url))
    await session.flush()

    session.add(Recipe(title="дубль", servings=1, source_url=url))
    with pytest.raises(Exception, match="uq_recipes_source_url"):
        await session.flush()


def test_models_and_migration_agree() -> None:
    """`alembic check`: the invariant that rots first once M2-M7 add columns."""
    from alembic import command
    from alembic.util.exc import AutogenerateDiffsDetected

    from app.core.migrate import alembic_config
    from tests.conftest import test_database_url

    async def run() -> None:
        await asyncio.to_thread(command.check, alembic_config(url=test_database_url()))

    try:
        asyncio.run(run())
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"models and migration have diverged: {exc}")
