"""initial schema

Every table of the project is created here, so that later modules never have to
race each other with migrations (TZ-M1 section 2).

Generated with `alembic revision --autogenerate`, then hand-edited to add the
things autogenerate cannot know about: the extensions, and the seed rows for
the ingredient-category vocabulary.

Revision ID: 0001
Revises:
Create Date: 2026-07-28 08:54:02.683307+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Reference vocabulary shared by `ingredients.category` and
# `cook_coefficients.ingredient_category`. Seeded here because both FK to it.
# The cooking factors themselves are domain data and are loaded by M4 from
# data/cook_coefficients.csv.
INGREDIENT_CATEGORIES: list[dict[str, object]] = [
    {"code": "мясо", "title": "Мясо", "sort_order": 10},
    {"code": "птица", "title": "Птица", "sort_order": 20},
    {"code": "рыба", "title": "Рыба и морепродукты", "sort_order": 30},
    {"code": "яйца", "title": "Яйца", "sort_order": 40},
    {"code": "молочка", "title": "Молочные продукты", "sort_order": 50},
    {"code": "овощи", "title": "Овощи", "sort_order": 60},
    {"code": "фрукты", "title": "Фрукты и ягоды", "sort_order": 70},
    {"code": "грибы", "title": "Грибы", "sort_order": 80},
    {"code": "крупы", "title": "Крупы", "sort_order": 90},
    {"code": "макароны", "title": "Макаронные изделия", "sort_order": 100},
    {"code": "бобовые", "title": "Бобовые", "sort_order": 110},
    {"code": "мука", "title": "Мука и выпечка", "sort_order": 120},
    {"code": "масла", "title": "Масла и жиры", "sort_order": 130},
    {"code": "орехи", "title": "Орехи и семена", "sort_order": 140},
    {"code": "специи", "title": "Специи и приправы", "sort_order": 150},
    {"code": "соусы", "title": "Соусы", "sort_order": 160},
    {"code": "сладости", "title": "Сахар и сладости", "sort_order": 170},
    {"code": "напитки", "title": "Напитки", "sort_order": 180},
    {"code": "прочее", "title": "Прочее", "sort_order": 900},
]


def upgrade() -> None:
    # Must come first: every VECTOR column below depends on it, and the
    # pgvector image only installs the extension files — it does not run
    # CREATE EXTENSION. Doing it here rather than in an initdb hook is also
    # what makes a restored dump and the test database work, since initdb
    # hooks only fire on a brand-new volume.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # Trigram indexes for ingredient / product / recipe-title lookup.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('month_budget_kop', sa.Integer(), nullable=True),
    sa.Column('meal_split', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"breakfast": 0.25, "lunch": 0.35, "dinner": 0.30, "snack": 0.10}\'::jsonb'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_families_name_not_blank')),
    sa.CheckConstraint('month_budget_kop IS NULL OR month_budget_kop >= 0', name=op.f('ck_families_month_budget_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_families'))
    )
    op.create_table('ingredient_categories',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='100', nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_ingredient_categories'))
    )
    op.create_table('parse_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('store', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Enum('schedule', 'manual', name='trigger', native_enum=False, create_constraint=True, length=32), server_default='schedule', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'ok', 'partial', 'failed', name='status', native_enum=False, create_constraint=True, length=32), server_default='running', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at', name=op.f('ck_parse_runs_finished_after_started')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_runs'))
    )
    op.create_index('ix_parse_runs_store_started_at', 'parse_runs', ['store', sa.literal_column('started_at DESC')], unique=False)
    op.create_index('ix_parse_runs_store_started_at_ok', 'parse_runs', ['store', sa.literal_column('started_at DESC')], unique=False, postgresql_where=sa.text("status = 'ok'"))
    op.create_table('recipes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meal_type', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('cook_method', sa.Enum('boil', 'fry', 'bake', 'stew', 'raw', name='cook_method', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('cook_minutes', sa.Integer(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('servings', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('active', 'quarantine', 'archived', name='status', native_enum=False, create_constraint=True, length=32), server_default='active', nullable=False),
    sa.Column('quarantine_reason', sa.Text(), nullable=True),
    sa.Column('nutrition_incomplete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('kcal_per_serving', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('protein_per_serving', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('fat_per_serving', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('carb_per_serving', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('raw_grams_per_serving', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nutrition_calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(384), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("meal_type <@ ARRAY['breakfast', 'lunch', 'dinner', 'snack']::text[]", name=op.f('ck_recipes_meal_type_values')),
    sa.CheckConstraint('cook_minutes IS NULL OR cook_minutes > 0', name=op.f('ck_recipes_cook_minutes_positive')),
    sa.CheckConstraint('length(btrim(title)) > 0', name=op.f('ck_recipes_title_not_blank')),
    sa.CheckConstraint('servings > 0', name=op.f('ck_recipes_servings_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('source_url', name='uq_recipes_source_url')
    )
    op.create_index('ix_recipes_cook_minutes', 'recipes', ['cook_minutes'], unique=False)
    op.create_index('ix_recipes_embedding_hnsw', 'recipes', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_recipes_kcal_per_serving', 'recipes', ['kcal_per_serving'], unique=False, postgresql_where=sa.text("status = 'active' AND nutrition_incomplete = false"))
    op.create_index('ix_recipes_meal_type', 'recipes', ['meal_type'], unique=False, postgresql_using='gin')
    op.create_index('ix_recipes_tags', 'recipes', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_recipes_title_trgm', 'recipes', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('cook_coefficients',
    sa.Column('ingredient_category', sa.Text(), nullable=False),
    sa.Column('cook_method', sa.Enum('boil', 'fry', 'bake', 'stew', 'raw', name='cook_method', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('weight_factor', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('weight_factor > 0 AND weight_factor <= 10', name=op.f('ck_cook_coefficients_weight_factor_range')),
    sa.ForeignKeyConstraint(['ingredient_category'], ['ingredient_categories.code'], name=op.f('fk_cook_coefficients_ingredient_category_ingredient_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ingredient_category', 'cook_method', name=op.f('pk_cook_coefficients'))
    )
    op.create_table('family_members',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('family_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'high', name='activity_level', native_enum=False, create_constraint=True, length=32), server_default='moderate', nullable=False),
    sa.Column('kcal_override', sa.Integer(), nullable=True),
    sa.Column('restrictions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("birth_date > DATE '1900-01-01'", name=op.f('ck_family_members_birth_date_sane')),
    sa.CheckConstraint('height_cm IS NULL OR (height_cm > 30 AND height_cm < 300)', name=op.f('ck_family_members_height_range')),
    sa.CheckConstraint('kcal_override IS NULL OR kcal_override BETWEEN 500 AND 8000', name=op.f('ck_family_members_kcal_override_range')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_family_members_name_not_blank')),
    sa.CheckConstraint('weight_kg > 0 AND weight_kg < 400', name=op.f('ck_family_members_weight_range')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_family_members_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_family_members'))
    )
    op.create_index('ix_family_members_family_id', 'family_members', ['family_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('kcal_100', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_100', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fat_100', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('carb_100', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('nutrition_source', sa.Text(), nullable=True),
    sa.Column('density_g_per_ml', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('piece_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(384), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('carb_100 IS NULL OR (carb_100 >= 0 AND carb_100 <= 100)', name=op.f('ck_ingredients_carb_range')),
    sa.CheckConstraint('density_g_per_ml IS NULL OR density_g_per_ml > 0', name=op.f('ck_ingredients_density_positive')),
    sa.CheckConstraint('fat_100 IS NULL OR (fat_100 >= 0 AND fat_100 <= 100)', name=op.f('ck_ingredients_fat_range')),
    sa.CheckConstraint('kcal_100 IS NULL OR kcal_100 >= 0', name=op.f('ck_ingredients_kcal_non_negative')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_ingredients_name_not_blank')),
    sa.CheckConstraint('name = lower(name)', name=op.f('ck_ingredients_name_is_lowercase')),
    sa.CheckConstraint('piece_grams IS NULL OR piece_grams > 0', name=op.f('ck_ingredients_piece_grams_positive')),
    sa.CheckConstraint('protein_100 IS NULL OR (protein_100 >= 0 AND protein_100 <= 100)', name=op.f('ck_ingredients_protein_range')),
    sa.ForeignKeyConstraint(['category'], ['ingredient_categories.code'], name=op.f('fk_ingredients_category_ingredient_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients')),
    sa.UniqueConstraint('name', name='uq_ingredients_name')
    )
    op.create_index('ix_ingredients_category', 'ingredients', ['category'], unique=False)
    op.create_index('ix_ingredients_embedding_hnsw', 'ingredients', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_ingredients_name_trgm', 'ingredients', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('meal_plans',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('family_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'done', 'cancelled', name='status', native_enum=False, create_constraint=True, length=32), server_default='draft', nullable=False),
    sa.Column('store', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('basket_comparison', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days BETWEEN 1 AND 14', name=op.f('ck_meal_plans_days_range')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_meal_plans_family_id_families'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plans'))
    )
    op.create_index('ix_meal_plans_family_id_status', 'meal_plans', ['family_id', 'status'], unique=False)
    op.create_index('ix_meal_plans_start_date', 'meal_plans', ['start_date'], unique=False)
    op.create_index('uq_meal_plans_one_active', 'meal_plans', ['family_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('fridge',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('family_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'purchase', 'plan_surplus', name='source', native_enum=False, create_constraint=True, length=32), server_default='manual', nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grams > 0', name=op.f('ck_fridge_grams_positive')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_fridge_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_fridge_ingredient_id_ingredients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], name=op.f('fk_fridge_plan_id_meal_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fridge'))
    )
    op.create_index('ix_fridge_expires_at', 'fridge', ['expires_at'], unique=False)
    op.create_index('ix_fridge_family_id_ingredient_id', 'fridge', ['family_id', 'ingredient_id'], unique=False)
    op.create_table('plan_meals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('slot_index', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('alternates', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('cooked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day >= 1', name=op.f('ck_plan_meals_day_is_one_based')),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], name=op.f('fk_plan_meals_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_plan_meals_recipe_id_recipes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_meals')),
    sa.UniqueConstraint('plan_id', 'day', 'meal_type', 'slot_index', name='uq_plan_meals_slot')
    )
    op.create_index('ix_plan_meals_plan_id_day', 'plan_meals', ['plan_id', 'day'], unique=False)
    op.create_index('ix_plan_meals_recipe_id', 'plan_meals', ['recipe_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_amount', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('raw_unit', sa.Text(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cook_method', sa.Enum('boil', 'fry', 'bake', 'stew', 'raw', name='cook_method', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('grams IS NULL OR grams >= 0', name=op.f('ck_recipe_ingredients_grams_non_negative')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_recipe_ingredients_position_non_negative')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_recipe_ingredients_ingredient_id_ingredients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients')),
    sa.UniqueConstraint('recipe_id', 'position', name='uq_recipe_ingredients_recipe_id_position')
    )
    op.create_index('ix_recipe_ingredients_ingredient_id', 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_table('store_products',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('store', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_normalized', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('pack_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pack_qty', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('pack_unit', sa.Enum('g', 'ml', 'piece', name='pack_unit', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('pack_raw_text', sa.Text(), nullable=True),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('candidate_ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('match_status', sa.Enum('unmatched', 'candidate', 'auto', 'confirmed', 'rejected', name='match_status', native_enum=False, create_constraint=True, length=32), server_default='unmatched', nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('match_source', sa.Enum('rule', 'embedding', 'manual', name='match_source', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(384), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('embedding_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('match_confidence IS NULL OR (match_confidence >= 0 AND match_confidence <= 1)', name=op.f('ck_store_products_match_confidence_range')),
    sa.CheckConstraint('pack_grams IS NULL OR pack_grams > 0', name=op.f('ck_store_products_pack_grams_positive')),
    sa.ForeignKeyConstraint(['candidate_ingredient_id'], ['ingredients.id'], name=op.f('fk_store_products_candidate_ingredient_id_ingredients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_store_products_ingredient_id_ingredients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_products')),
    sa.UniqueConstraint('store', 'external_id', name='uq_store_products_store_external_id')
    )
    op.create_index('ix_store_products_embedding_hnsw', 'store_products', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 24, 'ef_construction': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_store_products_ingredient_id_store', 'store_products', ['ingredient_id', 'store'], unique=False, postgresql_where=sa.text('ingredient_id IS NOT NULL'))
    op.create_index('ix_store_products_match_status', 'store_products', ['match_status'], unique=False, postgresql_where=sa.text("match_status = 'candidate'"))
    op.create_index('ix_store_products_name_trgm', 'store_products', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_store_products_store_category', 'store_products', ['store', 'category'], unique=False)
    op.create_table('weight_log',
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight_kg > 0 AND weight_kg < 400', name=op.f('ck_weight_log_weight_range')),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], name=op.f('fk_weight_log_member_id_family_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'date', name=op.f('pk_weight_log'))
    )
    op.create_table('expenses',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('family_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_kop', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('plan', 'manual', 'receipt', name='source', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=True),
    sa.Column('store', sa.Text(), nullable=True),
    sa.Column('store_product_id', sa.BigInteger(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_kop >= 0', name=op.f('ck_expenses_amount_non_negative')),
    sa.CheckConstraint('qty IS NULL OR qty > 0', name=op.f('ck_expenses_qty_positive')),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('fk_expenses_family_id_families'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], name=op.f('fk_expenses_plan_id_meal_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_product_id'], ['store_products.id'], name=op.f('fk_expenses_store_product_id_store_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_family_id_date', 'expenses', ['family_id', 'date'], unique=False)
    op.create_index('ix_expenses_plan_id', 'expenses', ['plan_id'], unique=False)
    op.create_index('ix_expenses_store_product_id', 'expenses', ['store_product_id'], unique=False)
    op.create_index('uq_expenses_plan', 'expenses', ['plan_id'], unique=True, postgresql_where=sa.text("source = 'plan'"))
    op.create_table('meal_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('plan_meal_id', sa.BigInteger(), nullable=True),
    sa.Column('recipe_id', sa.BigInteger(), nullable=True),
    sa.Column('eaten_fraction', sa.Numeric(precision=4, scale=3), server_default='1.0', nullable=False),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('kcal', sa.Numeric(precision=9, scale=2), server_default='0', nullable=False),
    sa.Column('protein', sa.Numeric(precision=9, scale=2), server_default='0', nullable=False),
    sa.Column('fat', sa.Numeric(precision=9, scale=2), server_default='0', nullable=False),
    sa.Column('carb', sa.Numeric(precision=9, scale=2), server_default='0', nullable=False),
    sa.Column('source', sa.Enum('plan', 'manual', 'llm', name='source', native_enum=False, create_constraint=True, length=32), server_default='manual', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('eaten_fraction > 0 AND eaten_fraction <= 5', name=op.f('ck_meal_log_eaten_fraction_range')),
    sa.CheckConstraint('kcal >= 0 AND protein >= 0 AND fat >= 0 AND carb >= 0', name=op.f('ck_meal_log_nutrition_non_negative')),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], name=op.f('fk_meal_log_member_id_family_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_meal_id'], ['plan_meals.id'], name=op.f('fk_meal_log_plan_meal_id_plan_meals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_meal_log_recipe_id_recipes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_log'))
    )
    op.create_index('ix_meal_log_date', 'meal_log', ['date'], unique=False)
    op.create_index('ix_meal_log_member_id_date', 'meal_log', ['member_id', 'date'], unique=False)
    op.create_index('ix_meal_log_recipe_id', 'meal_log', ['recipe_id'], unique=False)
    op.create_index('uq_meal_log_plan_meal_member', 'meal_log', ['plan_meal_id', 'member_id'], unique=True, postgresql_where=sa.text('plan_meal_id IS NOT NULL'))
    op.create_table('plan_meal_portions',
    sa.Column('plan_meal_id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('portion', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('kcal', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('protein', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('carb', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.CheckConstraint('portion > 0 AND portion <= 3', name=op.f('ck_plan_meal_portions_portion_range')),
    sa.ForeignKeyConstraint(['member_id'], ['family_members.id'], name=op.f('fk_plan_meal_portions_member_id_family_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_meal_id'], ['plan_meals.id'], name=op.f('fk_plan_meal_portions_plan_meal_id_plan_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_meal_id', 'member_id', name=op.f('pk_plan_meal_portions'))
    )
    op.create_table('price_history',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('price_kop', sa.Integer(), nullable=False),
    sa.Column('regular_price_kop', sa.Integer(), nullable=True),
    sa.Column('promo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_kop >= 0', name=op.f('ck_price_history_price_non_negative')),
    sa.CheckConstraint('regular_price_kop IS NULL OR regular_price_kop >= 0', name=op.f('ck_price_history_regular_price_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], name=op.f('fk_price_history_product_id_store_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'observed_at', name=op.f('pk_price_history'))
    )
    op.create_index('ix_price_history_observed_at', 'price_history', ['observed_at'], unique=False)
    op.create_table('shopping_items',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('store', sa.Text(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('planned_unit_price_kop', sa.Integer(), nullable=False),
    sa.Column('planned_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('surplus_grams', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bought', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('actual_unit_price_kop', sa.Integer(), nullable=True),
    sa.Column('bought_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_qty IS NULL OR actual_qty > 0', name=op.f('ck_shopping_items_actual_qty_positive')),
    sa.CheckConstraint('actual_unit_price_kop IS NULL OR actual_unit_price_kop >= 0', name=op.f('ck_shopping_items_actual_price_non_negative')),
    sa.CheckConstraint('planned_unit_price_kop >= 0', name=op.f('ck_shopping_items_planned_price_non_negative')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_shopping_items_qty_positive')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_shopping_items_ingredient_id_ingredients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], name=op.f('fk_shopping_items_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], name=op.f('fk_shopping_items_product_id_store_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_items')),
    sa.UniqueConstraint('plan_id', 'store', 'product_id', name='uq_shopping_items_plan_product')
    )
    op.create_index('ix_shopping_items_plan_id_store', 'shopping_items', ['plan_id', 'store'], unique=False)
    op.create_index('ix_shopping_items_product_id', 'shopping_items', ['product_id'], unique=False)
    # ### end Alembic commands ###

    op.bulk_insert(
        sa.table(
            "ingredient_categories",
            sa.column("code", sa.Text),
            sa.column("title", sa.Text),
            sa.column("sort_order", sa.SmallInteger),
        ),
        INGREDIENT_CATEGORIES,
    )


def downgrade() -> None:
    # Extensions are deliberately NOT dropped: other databases in the same
    # cluster may be using them.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopping_items_product_id', table_name='shopping_items')
    op.drop_index('ix_shopping_items_plan_id_store', table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index('ix_price_history_observed_at', table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('plan_meal_portions')
    op.drop_index('uq_meal_log_plan_meal_member', table_name='meal_log', postgresql_where=sa.text('plan_meal_id IS NOT NULL'))
    op.drop_index('ix_meal_log_recipe_id', table_name='meal_log')
    op.drop_index('ix_meal_log_member_id_date', table_name='meal_log')
    op.drop_index('ix_meal_log_date', table_name='meal_log')
    op.drop_table('meal_log')
    op.drop_index('uq_expenses_plan', table_name='expenses', postgresql_where=sa.text("source = 'plan'"))
    op.drop_index('ix_expenses_store_product_id', table_name='expenses')
    op.drop_index('ix_expenses_plan_id', table_name='expenses')
    op.drop_index('ix_expenses_family_id_date', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('weight_log')
    op.drop_index('ix_store_products_store_category', table_name='store_products')
    op.drop_index('ix_store_products_name_trgm', table_name='store_products', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_store_products_match_status', table_name='store_products', postgresql_where=sa.text("match_status = 'candidate'"))
    op.drop_index('ix_store_products_ingredient_id_store', table_name='store_products', postgresql_where=sa.text('ingredient_id IS NOT NULL'))
    op.drop_index('ix_store_products_embedding_hnsw', table_name='store_products', postgresql_using='hnsw', postgresql_with={'m': 24, 'ef_construction': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('store_products')
    op.drop_index('ix_recipe_ingredients_ingredient_id', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('ix_plan_meals_recipe_id', table_name='plan_meals')
    op.drop_index('ix_plan_meals_plan_id_day', table_name='plan_meals')
    op.drop_table('plan_meals')
    op.drop_index('ix_fridge_family_id_ingredient_id', table_name='fridge')
    op.drop_index('ix_fridge_expires_at', table_name='fridge')
    op.drop_table('fridge')
    op.drop_index('uq_meal_plans_one_active', table_name='meal_plans', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_meal_plans_start_date', table_name='meal_plans')
    op.drop_index('ix_meal_plans_family_id_status', table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index('ix_ingredients_name_trgm', table_name='ingredients', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_ingredients_embedding_hnsw', table_name='ingredients', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_ingredients_category', table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index('ix_family_members_family_id', table_name='family_members')
    op.drop_table('family_members')
    op.drop_table('cook_coefficients')
    op.drop_index('ix_recipes_title_trgm', table_name='recipes', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_recipes_tags', table_name='recipes', postgresql_using='gin')
    op.drop_index('ix_recipes_meal_type', table_name='recipes', postgresql_using='gin')
    op.drop_index('ix_recipes_kcal_per_serving', table_name='recipes', postgresql_where=sa.text("status = 'active' AND nutrition_incomplete = false"))
    op.drop_index('ix_recipes_embedding_hnsw', table_name='recipes', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_recipes_cook_minutes', table_name='recipes')
    op.drop_table('recipes')
    op.drop_index('ix_parse_runs_store_started_at_ok', table_name='parse_runs', postgresql_where=sa.text("status = 'ok'"))
    op.drop_index('ix_parse_runs_store_started_at', table_name='parse_runs')
    op.drop_table('parse_runs')
    op.drop_table('ingredient_categories')
    op.drop_table('families')
    # ### end Alembic commands ###
